### ISSUE TITLE
OSError wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by francisuk1989** [Nzt2/massann_dahua#3]
scans ok but this error whan making .xml file

Сканирование ОК, но эта ошибка вхан создание XML-файла

Traceback (most recent call last):                                                                                                                             ]  0%
  File "masscan_dahua.py", line 134, in <module>
    main()
  File "masscan_dahua.py", line 130, in main
    parse_result()
  File "masscan_dahua.py", line 52, in parse_result
    if Auth(line[3]):
  File "masscan_dahua.py", line 27, in Auth
    dll = ctypes.CDLL("./Dll/libdhnetsdk.so")
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./Dll/libdhnetsdk.so: wrong ELF class: ELFCLASS32

**Comment by Nzt2** [comment]
Добрый день я писал что пока на на линуксе не работает

**Comment by Celestial-intelligence** [comment]
Все потому что работает все через sdk.
Неизвестно даже из какой версии легитимной проги была изъята используемая библиотека.
Линукс поддерживают только несколько, уже давно устаревших, версий декстопного ПО для просмотра этих камер.

UPD: Рекомендую изучить эти репозитории:
https://github.com/mordredazazel/hikikomori
https://github.com/arthar360/TaniDVR
